# Cosyne 2020 NWB:N Tutorial - Extracellular Electrophysiology

## Introduction
In this tutorial, we will create fake data for a hypothetical extracellular electrophysiology experiment with a freely moving animal. The types of data we will convert are:
- Animal position
- LFP
- Spike times
- Trials
- Subject (species, strain, age, etc.) 

## Installing PyNWB
If you are in the tutorial using DANDI Hub, PyNWB is already installed. 
If participating from your own machine, install PyNWB using pip or conda:
- `pip install pynwb`
- `conda install -c conda-forge pynwb`

## Set up the NWB file
An NWB file represents a single session of an experiment. Each file must have a session description, identifier, and session start time. Create a new `NWBFile` object with those and additional metadata. For all PyNWB constructors, we recommend using keyword arguments.

In [1]:
from pynwb import NWBFile
from datetime import datetime
from dateutil import tz

start_time = datetime(2018, 4, 25, 2, 30, 3, tzinfo=tz.gettz('US/Pacific'))

nwb = NWBFile(session_description='Mouse exploring an open field',
              identifier='Mouse5_Day3',
              session_start_time=start_time,
              session_id='session_1234',                                # optional
              experimenter='My Name',                                   # optional
              lab='My Lab Name',                                        # optional
              institution='University of My Institution',               # optional
              related_publications='DOI:10.1016/j.neuron.2016.12.011')  # optional
nwb

root pynwb.file.NWBFile at 0x1327488823048
Fields:
  experimenter: ['My Name']
  file_create_date: [datetime.datetime(2020, 2, 24, 23, 48, 42, 740487, tzinfo=tzlocal())]
  identifier: Mouse5_Day3
  institution: University of My Institution
  lab: My Lab Name
  related_publications: ['DOI:10.1016/j.neuron.2016.12.011']
  session_description: Mouse exploring an open field
  session_id: session_1234
  session_start_time: 2018-04-25 02:30:03-07:00
  timestamps_reference_time: 2018-04-25 02:30:03-07:00

## Subject information
Create a `Subject` object to store information about the experimental subject, such as age, species, genotype, sex, and a freeform description. And set `nwb.subject` to the `Subject` object.


<img src="images/subject_diagram.png" width="600">

In [2]:
from pynwb.file import Subject

nwb.subject = Subject(age='9 months', 
                      description='mouse 5',
                      species='Mus musculus', 
                      sex='M')

## Position
The `Position` object is a special type of object called a `MultiContainerInterface`. It holds one or more `SpatialSeries` objects. 

<img src="images/spatial_series.png" width="600">

## SpatialSeries
`SpatialSeries` is a subclass of `TimeSeries`. `TimeSeries` is a common base class for measurements sampled over time, and provides fields for data and time (regularly or irregularly sampled).

<img src="images/position.png" width="800">

Create a `SpatialSeries` object named `'position'` with some fake data.

In [3]:
import numpy as np
from pynwb.behavior import SpatialSeries, Position

position_data = np.array([np.linspace(0, 10, 100),
                          np.linspace(1, 8, 100)]).T
spatial_series_object = SpatialSeries(
    name='position', 
    data=position_data,
    reference_frame='unknown',
    timestamps=np.linspace(0, 100) / 200)

Then, create a `Position` object which contains the `SpatialSeries` object you just created.

In [4]:
pos_obj = Position(spatial_series=spatial_series_object)

Finally, create a processing module named `'behavior'` in the NWB file and add the `Position` object to the processing module.

In [5]:
behavior_module = nwb.create_processing_module(
    name='behavior',
    description='processed behavioral data')

behavior_module.add(pos_obj)

Position pynwb.behavior.Position at 0x1327772280072
Fields:
  spatial_series: {
    position <class 'pynwb.behavior.SpatialSeries'>
  }

## Write to file

In [6]:
from pynwb import NWBHDF5IO

with NWBHDF5IO('ecephys_tutorial.nwb', 'w') as io:
    io.write(nwb)

## Trials

<img src="images/trials.png" width="500">

`DynamicTable` objects are used to store tabular metadata throughout NWB, including electrodes and sorted units. They offer flexibility for tabular data by allowing required columns, optional columns, and custom columns.

Trials are stored in a `TimeIntervals` object which subclasses `DynamicTable`. Here, we are adding a column named `'correct'`, which will be a boolean array.

In [7]:
nwb.add_trial_column(name='correct', description='whether the trial was correct')
nwb.add_trial(start_time=1.0, stop_time=5.0, correct=True)
nwb.add_trial(start_time=6.0, stop_time=10.0, correct=False)

## Electrodes table
Extracellular electrodes are stored in a `electrodes` table, which is also a `DynamicTable`. `electrodes` has several required fields: x, y, z, impedence, location, filtering, and electrode_group.

<img src="images/electrodes_table.png" width="300">

Here, we also demonstrate how to add optional columns to a table by adding the `'label'` column.

In [8]:
nwb.add_electrode_column('label', 'label of electrode')
shank_channels = [4, 3]  # set up 4 shanks with 3 electrodes each

electrode_counter = 0
device = nwb.create_device('array')
for shankn, nelecs in enumerate(shank_channels):
    # create an electrode group for this shank
    electrode_group = nwb.create_electrode_group(
       name='shank{}'.format(shankn),
       description='electrode group for shank {}'.format(shankn),
       device=device,
       location='brain area')
    # add electrodes to the electrode table
    for ielec in range(nelecs):
        nwb.add_electrode(
           x=5.3, y=1.5, z=8.5, imp=np.nan,
           location='unknown', filtering='unknown',
           group=electrode_group,
           label='shank{}elec{}'.format(shankn, ielec))
        electrode_counter += 1

## Links
In the above loop, we create `ElectrodeGroup` objects using `nwb.create_electrode_group`. When we add an electrode, we pass in the `ElectrodeGroup` object for the `'group'` argument. This creates a reference from the `electrodes` table to individual `ElectrodeGroup` objects, one per row.

In order to create our `ElectricalSeries` object, we will also need to create a `DynamicTableRegion` of electrodes. A `DynamicTableRegion` is a type of link that allows you to reference specific rows of a `DynamicTable`.

In [9]:
# create a table region object that refs to a set of rows of the table by index
all_table_region = nwb.create_electrode_table_region(
  list(range(electrode_counter)), 'all electrodes')

## LFP
`LFP` is another `MultiContainerInterface`. It holds one or more `ElectricalSeries` objects, which are `TimeSeries`. Here, we put an `ElectricalSeries` named `'lfp'` in an `LFP` object, in a `ProcessingModule` named `'ecephys'`.
<img src="images/lfp.png" width="800">

In [10]:
from pynwb.ecephys import ElectricalSeries, LFP

lfp_data = np.random.randn(100, 7)
ecephys_module = nwb.create_processing_module(
    name='ecephys',
    description='extracellular electrophysiology data')
ecephys_module.add_data_interface(
LFP(ElectricalSeries(name='lfp', 
                     data=lfp_data, 
                     electrodes=all_table_region, 
                     rate=200.)))

## Spike Times
Spike times are stored in another `DynamicTable` of subtype `Units`. The main `Units` table is at `/units` in the HDF5 file. You can add columns to the `Units` table just like you did for `electrodes`. Here, we generate some random spike data and populate the table. 

In [11]:
firing_rate = 20
n_units = 10
for n_units_per_shank in range(n_units):
    n_spikes = np.random.poisson(lam=20)
    spike_times = np.cumsum(np.random.exponential(1/firing_rate, n_spikes))
    nwb.add_unit(spike_times=spike_times)

## Ragged arrays

Spike times are an example of a ragged array - it's like a matrix, but each row has a different number of elements. We can represent this type of data as an indexed column of the units `DynamicTable`. These indexed columns have two components, the vector data object that holds the data and the vector index object that holds the indices in the vector that indicate the row breaks.

<img src="images/ragged_array.png" width="800">

## Write the file

In [12]:
with NWBHDF5IO('ecephys_tutorial.nwb', 'w') as io:
    io.write(nwb)

## Reading NWB data
Data arrays are read passively from the file. Calling `TimeSeries.data` does not read the data values, but presents an h5py object that can be indexed to read data. Index this array just like a numpy array to read only a specific section of the array, or use the `[:]` operator to read the entire thing.

In [15]:
with NWBHDF5IO('ecephys_tutorial.nwb', 'r') as io:
    nwb2 = io.read()

    print(nwb2.processing['ecephys']['LFP'].electrical_series['lfp'].data[:])

[[-8.39253639e-02  6.66137362e-02 -6.85379755e-01  9.80158724e-01
  -8.05334907e-01 -1.11771734e-01 -1.85772591e-01]
 [ 5.06940198e-01  1.57981207e+00 -1.70678934e-01 -5.00910183e-01
  -6.54950861e-01 -3.08091170e-01 -1.24479837e-01]
 [ 5.67313760e-01 -5.57082673e-02  4.24177913e-01  3.24552697e-01
  -2.54629433e-01 -1.14224536e-01  1.48253814e+00]
 [ 2.85390614e-02 -7.51065605e-01  1.62587469e+00  9.29963541e-01
  -1.54351646e+00 -1.14957322e+00  1.97718305e-01]
 [-8.19019919e-01 -1.86185498e+00  9.56568321e-01 -4.51384514e-01
   7.43905114e-01 -1.03825392e+00 -7.61528632e-01]
 [-9.36131989e-01 -2.37430480e-01 -2.58361543e-01 -1.46038834e+00
  -2.56266202e-01  6.85689867e-01  3.60342003e-01]
 [ 1.32314733e+00 -6.10638193e-01 -1.56954211e+00  3.47819050e-01
   6.61822615e-01 -1.22836001e-01  8.43100885e-01]
 [ 1.04677137e+00  1.25098812e+00 -1.08219729e-01 -3.78475245e-01
  -1.24281412e+00 -1.25185890e+00 -1.00370911e-01]
 [ 1.65943879e+00  1.46596028e+00  1.32841107e+00 -1.57377392e+0

## Accessing data regions
It is often preferable to read only a portion of the data. To do this, index or slice into the `'data'` property. The following takes elements 0:10 in the first dimension and 0:5 in the second dimension from the LFP data we have written.

Accessing ragged arrays is similar- `nwb2.units['spike_times'][0]` only reads the times from the 0th unit.

In [20]:
io = NWBHDF5IO('ecephys_tutorial.nwb', 'r')
nwb2 = io.read()

print('section of lfp:')
print(nwb2.processing['ecephys']['LFP'].electrical_series['lfp'].data[:10,:5])
print('')
print('spike times from 0th unit:')
print(nwb2.units['spike_times'][0])
io.close()

section of lfp:
[[-0.08392536  0.06661374 -0.68537976  0.98015872 -0.80533491]
 [ 0.5069402   1.57981207 -0.17067893 -0.50091018 -0.65495086]
 [ 0.56731376 -0.05570827  0.42417791  0.3245527  -0.25462943]
 [ 0.02853906 -0.7510656   1.62587469  0.92996354 -1.54351646]
 [-0.81901992 -1.86185498  0.95656832 -0.45138451  0.74390511]
 [-0.93613199 -0.23743048 -0.25836154 -1.46038834 -0.2562662 ]
 [ 1.32314733 -0.61063819 -1.56954211  0.34781905  0.66182261]
 [ 1.04677137  1.25098812 -0.10821973 -0.37847525 -1.24281412]
 [ 1.65943879  1.46596028  1.32841107 -1.57377392  0.72509681]
 [-1.75459275 -0.36737557 -0.23261417 -0.51129335 -1.98824611]]

spike times from first unit:
[0.21959133 0.3741248  2.24541247 1.85516824 2.21273244 0.17871795
 1.16084319 0.987212   0.21912867]


# Learn more!

## Python tutorials
### See our tutorials for more details about your data type:
* [Extracellular electrophysiology](https://pynwb.readthedocs.io/en/stable/tutorials/domain/ecephys.html#sphx-glr-tutorials-domain-ecephys-py)
* [Calcium imaging](https://pynwb.readthedocs.io/en/stable/tutorials/domain/ophys.html#sphx-glr-tutorials-domain-ophys-py)
* [Intracellular electrophysiology](https://pynwb.readthedocs.io/en/stable/tutorials/domain/icephys.html#sphx-glr-tutorials-domain-icephys-py)

### Check out other tutorials that teach advanced NWB topics:
* [Iterative data write](https://pynwb.readthedocs.io/en/stable/tutorials/general/iterative_write.html#sphx-glr-tutorials-general-iterative-write-py)
* [Extensions](https://pynwb.readthedocs.io/en/stable/tutorials/general/extensions.html#sphx-glr-tutorials-general-extensions-py)
* [Advanced HDF5 I/O](https://pynwb.readthedocs.io/en/stable/tutorials/general/advanced_hdf5_io.html#sphx-glr-tutorials-general-advanced-hdf5-io-py)


## MATLAB tutorials
* [Extracellular electrophysiology](https://neurodatawithoutborders.github.io/matnwb/tutorials/html/ecephys.html)
* [Calcium imaging](https://neurodatawithoutborders.github.io/matnwb/tutorials/html/ophys.html)
* [Intracellular electrophysiology](https://neurodatawithoutborders.github.io/matnwb/tutorials/html/icephys.html)
